sequenceDiagram
    Note over Browser: User write a note
    Note over Browser: User click save button
    Browser->>+Server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/new_note

    Note over Server: Server recieves note text
    Note over Server: Server saves the note text in DB
    Note over Browser: Form submit reload page
    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/notes

    Server-->>Browser: HTML document
    

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    Server-->>Browser: CSS file

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    Server-->>Browser: JavaScript file

    Note over Browser: The browser execute the JavaScript code that fetches <br> the JSON that contain the notes from the server

    Browser->>Server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    Server-->>Browser: [{"content":"jjj","date":"2026-03-22T19:02:20.982Z"}, ... ]

    Note over Browser: The browser executes the callback <br> function that renders the notes
    